name: diffusion_env_cuda
channels:
  - nvidia
  - pytorch
  - defaults
dependencies:
  - python=3.12
  - matplotlib
  - numpy<2
  - scikit-image
  - pandas
  - scipy
  - jupyter
  - tqdm
  - onnx
  - pytorch
  - torchvision
  - pytorch-cuda=12.1
